name: scorevariants
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy=1.21.2
  - pytorch=1.10.1
  - setuptools=59.5.0
  - h5py
  - pip
  - pip:
      - pytorch-lightning
      - biopython
      - pysam
      - gatkPythonPackageArchive.zip
