language: java
sudo: required
dist: trusty

jdk:
- oraclejdk8

env:
  matrix:
  - RUN_CNV_SOMATIC_WDL=true TEST_DOCKER=false RUN_M2_WDL=false
  - RUN_CNV_SOMATIC_WDL=false TEST_DOCKER=false RUN_M2_WDL=false
  - RUN_CNV_SOMATIC_WDL=false TEST_DOCKER=true RUN_M2_WDL=false
  - RUN_CNV_SOMATIC_WDL=false TEST_DOCKER=false RUN_M2_WDL=true
  global:
  #limit gradle jvm memory usage
  - GRADLE_OPTS=-Xmx512m
  - secure: Da9Brv5WKCE3z0bp5u52X1Rqul5C/r7idGj/yLhHnlEvHXPDQHaGXEQw4fNhRkB586lx6xilO8sra2FHoLDMKsqwE0h2+NKsrHQepTSFOR/fp/otoA/kiBue23ZfhsAEFn/uliVU36xLkt+LsyVqSKa+9JKDA5z1hXSemXGGVGw=

before_install:
# Added from hellbender public
- sudo mkdir -p /usr/local/lib/R/
- sudo mkdir -p site-library
- sudo ln -sFv ~/site-library /usr/local/lib/R/site-library
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
- sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/"
- sudo apt-get update
- sudo apt-get install -y --force-yes r-base-dev=3.1.3-1trusty
- sudo apt-get install -y --force-yes r-base-core=3.1.3-1trusty
- sudo Rscript scripts/install_R_packages.R
# Install git-lfs, and fetch the large test files
- sudo bash scripts/install_git_lfs.sh
# Download Cromwell jar
- if [[ $RUN_CNV_SOMATIC_WDL == true ]] || [[ $RUN_M2_WDL == true ]]; then
    wget -O ~/cromwell-0.25.jar https://github.com/broadinstitute/cromwell/releases/download/25/cromwell-25.jar;
  fi
# Download Picard jar
- if [[ $RUN_M2_WDL == true ]]; then
    wget -O ~/picard.jar https://github.com/broadinstitute/picard/releases/download/2.9.0/picard.jar;
  fi

install:
- if [[ $RUN_CNV_SOMATIC_WDL == true ]]; then 
    ./gradlew shadowJar;
  elif [[$RUN_M2_WDL == true ]]; then
    ./gradlew shaowJar;
  elif [[$TEST_DOCKER == false ]]; then
    ./gradlew assemble;
  fi 

script:
- echo "Branch  ${TRAVIS_BRANCH}"
- echo `git rev-parse ${TRAVIS_BRANCH}`

- if [[ $RUN_CNV_SOMATIC_WDL == true ]]; then
    echo "Running CNV somatic workflows";
    bash scripts/cnv_cromwell_tests/somatic/run_cnv_somatic_workflows.sh;
  elif [[ $RUN_M2_WDL == true ]]; then
    sudo bash scripts/m2_cromwell_tests/run_m2_wdl.sh;
  elif [[ $TEST_DOCKER == true ]]; then
    echo "Building docker image with unit tests..." ;
    echo "${TRAVIS_BRANCH}" ;
    cp -rfp scripts/docker/Dockerfile . ;
    cp -rfp scripts/docker/build_docker.sh . ;
    sudo bash build_docker.sh  -e `git rev-parse ${TRAVIS_BRANCH}` -s;
  else
    ./gradlew check;
  fi

after_success:
- if [[ $RUN_CNV_SOMATIC_WDL == false ]] && [[ $TEST_DOCKER == false ]] && [[ $RUN_M2_WDL == false ]]; then
    ./gradlew jacocoTestReport coveralls;
  fi

after_failure:
- dmesg | tail -100
